## 프로젝트 소개
본 프로젝트는 주택 가격에 영향을 줄 수 있는 79개의 특성들을 이용하여 주택 가격을 예측하는 것이 목표입니다.

## 파일 구성
 - **train.csv**: 학습 데이터
 - **test.csv**: 평가 데이터
 - **submission.csv**: 제출 데이터

## 특성 설명
 - `SalePrice`: 부동산의 판매 가격 (달러). **레이블 (종속변수, 타겟변수)**.
 - `MSSubClass` : 건물 등급
 - `MSZoning` : 일반 구역 분류
 - `LotFrontage` : 부동산에 연결된 거리의 선형 피트
 - `LotArea` : 평방 피트 단위의 부지 크기
 - `Street` : 도로 유형
 - `Alley` : 골목 유형
 - `LotShape` : 부지유형
 - `LandContour` : 부동산의 평탄도
 - `Utilities` : 사용 가능한 유틸리티 유형
 - `LotConfig` : 부지 구성
 - `LandSlope` : 부동산의 경사
 - `Neighborhood` : 인근유형. 물리적 위치
 - `Condition1` : 주요 도로 또는 철도와의 근접성
 - `Condition2` : 주요 도로 또는 철도와의 근접성 (2번째 조건이 존재하는 경우)
 - `BldgType` : 주거 유형
 - `HouseStyle` : 주거 스타일
 - `OverallQual` : 전체 재료 및 마감 품질
 - `OverallCond` : 전체 상태 등급
 - `YearBuilt` : 준공일준공일
 - `YearRemodAdd` : 리모델링 날짜
 - `RoofStyle` : 지붕 유형
 - `RoofMatl` : 지붕 재료
 - `Exterior1st` : 주택주택 외장재
 - `Exterior2nd` : 주택 외장재 (하나 이상인 경우)
 - `MasVnrType` : 벽돌 베니어 유형
 - `MasVnrArea` : 벽돌 베니어 영역 (평방 피트)
 - `ExterQual` : 외장재 품질
 - `ExterCond` : 외장재의 현황
 - `Foundation` : 기초 유형
 - `BsmtQual` : 지하 높이
 - `BsmtCond` : 지하실 일반 상태
 - `BsmtExposure` : 워크 아웃 또는 정원 수준의 지하 벽
 - `BsmtFinType1` : 지하실 마감면의 품질
 - `BsmtFinSF1` : 유형 1 완성 된 평방 피트
 - `BsmtFinType2` : 두 번째 완성 된 영역의 품질 (있는 경우)
 - `BsmtFinSF2` : 유형 2 완성 된 평방 피트
 - `BsmtUnfSF` : 미완성 된 지하실 면적
 - `TotalBsmtSF` : 지하 총 평방 피트
 - `Heating` : 난방 유형
 - `HeatingQC` : 난방 품질 및 상태
 - `CentralAir` : 중앙 에어컨
 - `Electrical` : 전기 시스템
 - `1stFlrSF` : 1 층 평방 피트
 - `2ndFlrSF` : 2 층 평방 피트
 - `LowQualFinSF` : 저품질 마감 평방 피트 (모든 층)
 - `GrLivArea` : 지상 (지상) 거실 면적 평방 피트
 - `BsmtFullBath` : 지하 전체 욕실
 - `BsmtHalfBath` : 지하 반 욕실
 - `FullBath` : 등급 이상의 전체 욕실
 - `HalfBath` : 학년 이상의 Half Bath
 - `Bedroom` : 지하층 이상의 침실 수
 - `Kitchen` : 주방 수
 - `KitchenQual` : 주방 품질
 - `TotRmsAbvGrd` : 등급 이상의 총 방 (욕실은 포함되지 않음)
 - `Functional` : 홈 기능 등급
 - `Fireplaces` : 벽난로 수
 - `FireplaceQu` : 벽난로 품질
 - `GarageType` : 차고 위치
 - `GarageYrBlt` : 차고 건설 연도
 - `GarageFinish` : 차고 내부 마감
 - `GarageCars` : 차량 수용 가능 차고 크기
 - `GarageArea` : 차고 크기 (평방 피트)
 - `GarageQual` : 차고 품질
 - `GarageCond` : 차고 상태
 - `PavedDrive` : 포장 된 진입로
 - `WoodDeckSF` : 목재 데크 면적 (평방 피트)
 - `OpenPorchSF` : 평방 피트 단위의 오픈 현관 영역
 - `EnclosedPorch` : 밀폐 된 현관 영역 (평방 피트)
 - `3SsnPorch` : 3 계절 현관 면적 (평방 피트)
 - `ScreenPorch` : 스크린 포치 면적 (평방 피트)
 - `PoolArea` : 수영장 면적 (평방 피트)
 - `PoolQC` : 수영장 품질
 - `Fence` : 울타리 품질
 - `MiscFeature` : 다른 카테고리에서 다루지 않는 기타 기능
 - `MiscVal` : 기타 기능의 가치 (달러)
 - `MoSold` : 판매 월
 - `YrSold` : 판매 연도
 - `SaleType` : 판매 유형
 - `SaleCondition` : 판매 조건


## 평가 측도
 - **`rmsle`**: 낮을수록 좋음

## 최종 제출 안내
 - 분석이 모두 완료된 수강생은 최종 제출을 해야 합니다.
 - 최종 제출은
  과제 제출처럼 작성한 최종 ipynb 파일을 업로드 하시면 됩니다.

## 환경설정

In [ ]:
# !pip install jaen

In [21]:
import JAEN
from JAEN import list_data, download_data, Project

In [22]:
project_name = "주택 가격 예측" # 프로젝트 이름(수정하지 마세요)
email = "scsa24xxx" # 이메일(본인 SCSA 이메일 아이디 입력)

class_info = {
    'edu_name':'SCSA', # 과정명
    'edu_rnd':'24기', # 차수
    'edu_class':'SW' # "없음"이면 빈 문자열
}

# 프로젝트 생성
pjt = Project(project_name=project_name, class_info=class_info, email=email)

## import 모듈

In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings


# 경고 무시
warnings.filterwarnings('ignore')

## 다운로드 및 데이터 로드

In [24]:
download_data(project_name)

파일 다운로드 완료
====================

데이터셋: 주택 가격 예측
파일경로: data\sample_submission.csv

====================
파일 다운로드 완료
====================

데이터셋: 주택 가격 예측
파일경로: data\test.csv

====================
파일 다운로드 완료
====================

데이터셋: 주택 가격 예측
파일경로: data\train.csv

====================

In [26]:
# 데이터 로드
train = pd.read_csv("data/train.csv")
test = pd.read_csv("data/test.csv")
submission = pd.read_csv("data/sample_submission.csv")
submission # 제출 파일

        Id      SalePrice
0     1461  169277.052498
1     1462  187758.393989
2     1463  183583.683570
3     1464  179317.477511
4     1465  150730.079977
...    ...            ...
1454  2915  167081.220949
1455  2916  164788.778231
1456  2917  219222.423400
1457  2918  184924.279659
1458  2919  187741.866657

[1459 rows x 2 columns]

In [27]:
train.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

## ↓↓↓ 코드 구현 ↓↓↓
### 여기서부터 코드를 작성/수정하세요
#### - 데이터셋 로드, 전처리(필요시), 모델생성/컴파일, 학습

In [ ]:
# 데이터셋 준비(전처리), 모델설정, 학습

In [14]:
# 아래의 코드는 필요시 수정해서 사용합니다
pred = model.predict(test)
your_answer = pred
your_answer

In [ ]:
submission['SalePrice'] = your_answer

## 결과 제출 (수정하지 마세요)

### 순서대로 평가가 진행됩니다. 실행은 1회만 해주세요.

- 느리다고 중지 후 다시 평가 코드를 실행하는 경우 제출 과정에서 패널티가 발생할 수 있습니다. (제출 횟수 이슈 발생 가능)

- 전체 점수는 [평가시스템](http://manage.jaen.kr)에서 확인할 수 있습니다.
    - 프로젝트 > 손글씨 이미지분류 > 리더보드 > 같은 반 리더보드

- 아이디: 본인 이메일 아이디

In [38]:
pjt.submit(submission)

파일을 저장하였습니다. 파일명: submission-15-06-37.csv
제출 여부 :success
오늘 제출 횟수 : 1
제출 결과:0.21575188674745635