## 프로젝트 소개
본 프로젝트는 주택 가격에 영향을 줄 수 있는 79개의 특성들을 이용하여 주택 가격을 예측하는 것이 목표입니다.

## 파일 구성
 - **train.csv**: 학습 데이터
 - **test.csv**: 평가 데이터
 - **submission.csv**: 제출 데이터

## 특성 설명
 - `SalePrice`: 부동산의 판매 가격 (달러). **레이블 (종속변수, 타겟변수)**.
 - `MSSubClass` : 건물 등급
 - `MSZoning` : 일반 구역 분류
 - `LotFrontage` : 부동산에 연결된 거리의 선형 피트
 - `LotArea` : 평방 피트 단위의 부지 크기
 - `Street` : 도로 유형
 - `Alley` : 골목 유형
 - `LotShape` : 부지유형
 - `LandContour` : 부동산의 평탄도
 - `Utilities` : 사용 가능한 유틸리티 유형
 - `LotConfig` : 부지 구성
 - `LandSlope` : 부동산의 경사
 - `Neighborhood` : 인근유형. 물리적 위치
 - `Condition1` : 주요 도로 또는 철도와의 근접성
 - `Condition2` : 주요 도로 또는 철도와의 근접성 (2번째 조건이 존재하는 경우)
 - `BldgType` : 주거 유형
 - `HouseStyle` : 주거 스타일
 - `OverallQual` : 전체 재료 및 마감 품질
 - `OverallCond` : 전체 상태 등급
 - `YearBuilt` : 준공일준공일
 - `YearRemodAdd` : 리모델링 날짜
 - `RoofStyle` : 지붕 유형
 - `RoofMatl` : 지붕 재료
 - `Exterior1st` : 주택주택 외장재
 - `Exterior2nd` : 주택 외장재 (하나 이상인 경우)
 - `MasVnrType` : 벽돌 베니어 유형
 - `MasVnrArea` : 벽돌 베니어 영역 (평방 피트)
 - `ExterQual` : 외장재 품질
 - `ExterCond` : 외장재의 현황
 - `Foundation` : 기초 유형
 - `BsmtQual` : 지하 높이
 - `BsmtCond` : 지하실 일반 상태
 - `BsmtExposure` : 워크 아웃 또는 정원 수준의 지하 벽
 - `BsmtFinType1` : 지하실 마감면의 품질
 - `BsmtFinSF1` : 유형 1 완성 된 평방 피트
 - `BsmtFinType2` : 두 번째 완성 된 영역의 품질 (있는 경우)
 - `BsmtFinSF2` : 유형 2 완성 된 평방 피트
 - `BsmtUnfSF` : 미완성 된 지하실 면적
 - `TotalBsmtSF` : 지하 총 평방 피트
 - `Heating` : 난방 유형
 - `HeatingQC` : 난방 품질 및 상태
 - `CentralAir` : 중앙 에어컨
 - `Electrical` : 전기 시스템
 - `1stFlrSF` : 1 층 평방 피트
 - `2ndFlrSF` : 2 층 평방 피트
 - `LowQualFinSF` : 저품질 마감 평방 피트 (모든 층)
 - `GrLivArea` : 지상 (지상) 거실 면적 평방 피트
 - `BsmtFullBath` : 지하 전체 욕실
 - `BsmtHalfBath` : 지하 반 욕실
 - `FullBath` : 등급 이상의 전체 욕실
 - `HalfBath` : 학년 이상의 Half Bath
 - `Bedroom` : 지하층 이상의 침실 수
 - `Kitchen` : 주방 수
 - `KitchenQual` : 주방 품질
 - `TotRmsAbvGrd` : 등급 이상의 총 방 (욕실은 포함되지 않음)
 - `Functional` : 홈 기능 등급
 - `Fireplaces` : 벽난로 수
 - `FireplaceQu` : 벽난로 품질
 - `GarageType` : 차고 위치
 - `GarageYrBlt` : 차고 건설 연도
 - `GarageFinish` : 차고 내부 마감
 - `GarageCars` : 차량 수용 가능 차고 크기
 - `GarageArea` : 차고 크기 (평방 피트)
 - `GarageQual` : 차고 품질
 - `GarageCond` : 차고 상태
 - `PavedDrive` : 포장 된 진입로
 - `WoodDeckSF` : 목재 데크 면적 (평방 피트)
 - `OpenPorchSF` : 평방 피트 단위의 오픈 현관 영역
 - `EnclosedPorch` : 밀폐 된 현관 영역 (평방 피트)
 - `3SsnPorch` : 3 계절 현관 면적 (평방 피트)
 - `ScreenPorch` : 스크린 포치 면적 (평방 피트)
 - `PoolArea` : 수영장 면적 (평방 피트)
 - `PoolQC` : 수영장 품질
 - `Fence` : 울타리 품질
 - `MiscFeature` : 다른 카테고리에서 다루지 않는 기타 기능
 - `MiscVal` : 기타 기능의 가치 (달러)
 - `MoSold` : 판매 월
 - `YrSold` : 판매 연도
 - `SaleType` : 판매 유형
 - `SaleCondition` : 판매 조건


## 평가 측도
 - **`rmsle`**: 낮을수록 좋음

## 최종 제출 안내
 - 분석이 모두 완료된 수강생은 최종 제출을 해야 합니다.
 - 최종 제출은
  과제 제출처럼 작성한 최종 ipynb 파일을 업로드 하시면 됩니다.

## 환경설정

In [ ]:
# !pip install jaen

In [241]:
import JAEN
from JAEN import list_data, download_data, Project

In [302]:
project_name = "주택 가격 예측" # 프로젝트 이름(수정하지 마세요)
email = "scsa2406" # 이메일(본인 SCSA 이메일 아이디 입력)

class_info = {
    'edu_name':'SCSA', # 과정명
    'edu_rnd':'24기', # 차수
    'edu_class':'SW' # "없음"이면 빈 문자열
}

# 프로젝트 생성
pjt = Project(project_name=project_name, class_info=class_info, email=email)

## import 모듈

In [303]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings


# 경고 무시
warnings.filterwarnings('ignore')

## 다운로드 및 데이터 로드

In [304]:
download_data(project_name)

파일 다운로드 완료
====================

데이터셋: 주택 가격 예측
파일경로: data\sample_submission.csv

====================
파일 다운로드 완료
====================

데이터셋: 주택 가격 예측
파일경로: data\test.csv

====================
파일 다운로드 완료
====================

데이터셋: 주택 가격 예측
파일경로: data\train.csv

====================

In [305]:
# 데이터 로드
train = pd.read_csv("data/train.csv")
test = pd.read_csv("data/test.csv")
submission = pd.read_csv("data/sample_submission.csv")
submission # 제출 파일

        Id      SalePrice
0     1461  169277.052498
1     1462  187758.393989
2     1463  183583.683570
3     1464  179317.477511
4     1465  150730.079977
...    ...            ...
1454  2915  167081.220949
1455  2916  164788.778231
1456  2917  219222.423400
1457  2918  184924.279659
1458  2919  187741.866657

[1459 rows x 2 columns]

In [246]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

## ↓↓↓ 코드 구현 ↓↓↓
### 여기서부터 코드를 작성/수정하세요
#### - 데이터셋 로드, 전처리(필요시), 모델생성/컴파일, 학습

In [308]:
pd.DataFrame(train.isnull().sum()).sort_values(0, ascending=False)
for i in range(76):
    train.iloc[:, i].fillna(train.iloc[:, i].mode()[0], inplace = True)
    test.iloc[:, i].fillna(train.iloc[:, i].mode()[0], inplace = True)
def change(x):
    for j in range(len(items)):
        if items[j]==x:
            return j
for i in range(76):
    if train.iloc[:, i].dtype!='object': continue
    items = train.iloc[:, i].unique()
    train.iloc[:, i] = train.iloc[:, i].apply(lambda x: change(x))
    test.iloc[:, i] = test.iloc[:, i].apply(lambda x: change(x))

In [248]:
train

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,0,65.0,8450,0,0,0,0,0,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,0,80.0,9600,0,0,0,0,0,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,0,68.0,11250,0,0,1,0,0,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,0,60.0,9550,0,0,1,0,0,...,0,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,0,84.0,14260,0,0,1,0,0,...,0,0,0,0,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,0,62.0,7917,0,0,0,0,0,...,0,0,0,0,0,8,2007,WD,Normal,175000
1456,1457,20,0,85.0,13175,0,0,0,0,0,...,0,0,0,0,0,2,2010,WD,Normal,210000
1457,1458,70,0,66.0,9042,0,0,0,0,0,...,0,0,2,0,2500,5,2010,WD,Normal,266500
1458,1459,20,0,68.0,9717,0,0,0,0,0,...,0,0,0,0,0,4,2010,WD,Normal,142125
1459,1460,20,0,75.0,9937,0,0,0,0,0,...,0,0,0,0,0,6,2008,WD,Normal,147500

In [309]:
train.drop(['Alley'], axis = 1, inplace=True)
train.drop(['PoolQC', 'MiscFeature', 'Fence'], axis = 1, inplace=True)
test.drop(['Alley'], axis = 1, inplace=True)
test.drop(['PoolQC', 'MiscFeature', 'Fence'], axis = 1, inplace=True)

KeyError: "['Alley'] not found in axis"

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,1.000000,0.029800,-0.011949,0.040195,0.670669,-0.008916,-0.024071,0.014769,0.013324,-0.038192,...,0.120397,0.027209,0.110541,0.075696,0.024577,-0.010813,0.008429,-0.016932,-0.017712,0.428370
MSSubClass,0.029800,1.000000,0.237224,0.098344,-0.012867,0.021454,-0.185521,-0.016750,-0.015507,-0.073408,...,0.074019,-0.025664,-0.024167,0.016207,0.008362,0.002401,-0.002345,-0.004995,-0.025776,-0.066835
MSZoning,-0.011949,0.237224,1.000000,-0.016425,-0.093538,0.039678,-0.167918,-0.013396,-0.011167,-0.094747,...,0.086566,-0.037681,-0.075974,-0.026469,0.004953,0.005006,-0.022927,0.058948,0.068705,-0.005342
LotFrontage,0.040195,0.098344,-0.016425,1.000000,0.178883,-0.008713,0.106791,0.047261,-0.020556,0.027280,...,-0.053179,0.004672,0.035612,0.041596,-0.051460,0.026159,-0.007933,0.059209,0.077860,0.096102
LotArea,0.670669,-0.012867,-0.093538,0.178883,1.000000,0.014652,0.194447,0.081287,0.023841,0.058427,...,-0.002153,0.038609,0.095524,0.091482,-0.006382,-0.005586,-0.021163,0.002507,-0.036398,0.372106
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MoSold,-0.010813,0.002401,0.005006,0.026159,-0.005586,-0.042492,0.028312,-0.010752,0.011520,0.074662,...,-0.001148,-0.049375,-0.014881,0.023643,0.012712,1.000000,-0.009993,-0.012172,0.007342,0.014410
YrSold,0.008429,-0.002345,-0.022927,-0.007933,-0.021163,-0.007927,-0.019939,-0.053715,0.023231,0.072253,...,-0.006031,-0.037107,-0.012079,-0.025577,0.022640,-0.009993,1.000000,-0.022274,-0.005762,0.041850
SaleType,-0.016932,-0.004995,0.058948,0.059209,0.002507,0.021171,0.001435,-0.014537,0.057455,0.012120,...,-0.020309,0.018889,-0.036432,-0.004348,0.005921,-0.012172,-0.022274,1.000000,0.232149,0.038444
SaleCondition,-0.017712,-0.025776,0.068705,0.077860,-0.036398,0.022919,-0.004773,0.062826,0.019173,-0.013638,...,-0.067866,0.026808,-0.038899,0.082896,-0.025687,0.007342,-0.005762,0.232149,1.000000,0.090577
SalePrice,0.428370,-0.066835,-0.005342,0.096102,0.372106,0.031035,0.067894,0.008868,0.019717,0.019584,...,-0.002291,0.020350,0.016066,0.012560,-0.008143,0.014410,0.041850,0.038444,0.090577,1.000000

In [310]:
X_train = train.drop(['Id', 'SalePrice'], axis =1)
Y_train = train['SalePrice']
X_test = test.drop(['Id'], axis=1)

In [292]:
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(X_train, Y_train, test_size=0.25, random_state=0)
y_test

529     200624
491     133000
459     110000
279     192000
655      88000
         ...
583     325000
1245    178000
1390    235000
1375    239000
638      85000
Name: SalePrice, Length: 365, dtype: int64

In [253]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
X_scaled_train = MinMaxScaler().fit_transform(X_train)
x_train, x_test, y_train, y_test = train_test_split(X_scaled_train, Y_train, test_size=0.25, random_state=0)

In [295]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, StackingClassifier

knn2 = KNeighborsClassifier(n_neighbors=2)
knn3 = KNeighborsClassifier(n_neighbors=3)
knn4 = KNeighborsClassifier(n_neighbors=4)
knn5 = KNeighborsClassifier(n_neighbors=5)
lr = LogisticRegression()

dt3 = DecisionTreeClassifier(max_depth=3)
dt5 = DecisionTreeClassifier(max_depth=5)
dt10 = DecisionTreeClassifier(max_depth=10)

rand5 = RandomForestClassifier(max_depth=5).fit(X_train, Y_train)
rand = RandomForestClassifier().fit(X_train, Y_train)
gradient = GradientBoostingClassifier()

estimators = [('rf', RandomForestClassifier()),
               ('gb', GradientBoostingClassifier())]
stack = StackingClassifier(estimators=estimators,
                          final_estimator=LogisticRegression())

In [198]:
for idx, model in enumerate([knn2, knn3, knn4, knn5, lr, dt3, dt5, dt10, rand5, rand, gradient, stack]):
    model.fit(X_train, Y_train)

KeyboardInterrupt:

In [296]:
names = ['dt3', 'dt5', 'dt10', 'and5', 'rand', 'gradient', 'stack']
for idx, model in enumerate([dt3, dt5, dt10, rand5, rand, gradient, stack]):
    model.fit(x_train, y_train)
    name = names[idx]
    train_score = model.score(x_train, y_train)*100
    test_score = model.score(x_test, y_test)*100
    print(f'{name} Train Accuracy: {train_score:.2f}%')
    print(f'{name} Test Accuracy: {test_score:.2f}%')
    print()

dt3 Train Accuracy: 3.20%
dt3 Test Accuracy: 1.10%

dt5 Train Accuracy: 6.48%
dt5 Test Accuracy: 1.10%

dt10 Train Accuracy: 23.84%
dt10 Test Accuracy: 0.82%

and5 Train Accuracy: 33.42%
and5 Test Accuracy: 1.10%

KeyboardInterrupt:

In [255]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

linear = LinearRegression().fit(x_train, y_train)
print(linear.score(x_train, y_train), linear.score(x_test, y_test))

y_pred = rand.predict(x_test)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
print(rmse)

0.8794316153570594 0.6656152396520523
46984.895063593714

In [317]:
# 아래의 코드는 필요시 수정해서 사용합니다
from sklearn.preprocessing import StandardScaler, MinMaxScaler
X_train =StandardScaler().fit_transform(X_train)
X_test =  StandardScaler().fit_transform(X_test)
rand = RandomForestClassifier().fit(X_train, Y_train)
pred = rand.predict(X_test)
your_answer = pred
your_answer

array([ 97000, 151500, 192000, ..., 124900,  93500, 260000], dtype=int64)

In [318]:
submission['SalePrice'] = your_answer
pjt.submit(submission)

파일을 저장하였습니다. 파일명: submission-12-23-55.csv
제출 여부 :success
오늘 제출 횟수 : 5
제출 결과:0.205996320739241

## 결과 제출 (수정하지 마세요)

### 순서대로 평가가 진행됩니다. 실행은 1회만 해주세요.

- 느리다고 중지 후 다시 평가 코드를 실행하는 경우 제출 과정에서 패널티가 발생할 수 있습니다. (제출 횟수 이슈 발생 가능)

- 전체 점수는 [평가시스템](http://manage.jaen.kr)에서 확인할 수 있습니다.
    - 프로젝트 > 손글씨 이미지분류 > 리더보드 > 같은 반 리더보드

- 아이디: 본인 이메일 아이디

In [299]:
pjt.submit(submission)

파일을 저장하였습니다. 파일명: submission-12-07-07.csv
제출 여부 :success
오늘 제출 횟수 : 2
제출 결과:0.30258002997227823